# Generated by Django 3.2.16 on 2023-05-10 14:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='id_documento',
        ),
        migrations.AddField(
            model_name='documento',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
