# Generated by Django 3.2.16 on 2023-07-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculo',
            name='data_fim',
            field=models.DateField(null=True),
        ),
    ]
