# Generated by Django 3.2.16 on 2023-07-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinculo', '0003_vinculo_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculo',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
    ]
