# Generated by Django 3.2.16 on 2023-07-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinculo', '0004_alter_vinculo_data_fim'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinculo',
            name='situacao',
            field=models.BooleanField(default=True),
        ),
    ]
