# Generated by Django 3.2.16 on 2023-04-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='id_documento',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
