# Generated by Django 3.2.16 on 2023-04-28 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_alter_documento_id_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='modifyBy',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_modificados', to=settings.AUTH_USER_MODEL),
        ),
    ]
