# Generated by Django 3.2.16 on 2023-04-28 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_documento_modifyby'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
