# Generated by Django 3.2.16 on 2023-04-28 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Documento',
        ),
    ]
