# Generated by Django 3.2.16 on 2023-06-15 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0002_alter_cargo_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo',
            options={'ordering': ['-id']},
        ),
    ]
